# Override untuk Raspberry Pi (arm64)
# Gunakan bersama file utama:
# docker compose -f docker-compose.yml -f docker-compose.arm64.yml up -d

services:
  db:
    platform: linux/arm64

  redis:
    platform: linux/arm64

  backend:
    platform: linux/arm64

  celery_worker:
    platform: linux/arm64

  frontend:
    platform: linux/arm64

  nginx:
    platform: linux/arm64
